/* eslint-disable */
import { setupWorker } from 'msw/browser'

// @ts-nocheck
self.__WB_DISABLE_DEV_LOGS = true;

// This is a mock service worker script.
// It's automatically generated by msw when you run 'npx msw init public/'.
// Do not modify this file directly.

// If you want to customize the service worker behavior,
// create a custom service worker file and import this script.

// The following code is a template for the mock service worker.
// It will be replaced with actual handlers when the worker is initialized.

// @ts-ignore
const worker = setupWorker()
worker.start({
    serviceWorker: {
        url: '/mockServiceWorker.js'
    },
    quiet: true,
    onUnhandledRequest: 'bypass'
})

// This file will be replaced by the actual MSW service worker when initialized
